<?php

        session_start();
        $ROLLNO = $_SESSION['ROLLNO'];
        $Name = $_SESSION['Name'];
        $Phoneno = $_SESSION['Phoneno'];
        $Emailid = $_SESSION['Emailid'];
        $admissioncategory = $_SESSION['addmissioncategory'];
        $totalfees = $_SESSION['TotalAmountFee'] ;
        $Duefees = $_SESSION['Duefees'] ;
        $Reservation = $_SESSION['Reservation'];
        $apikey = 'rzp_test_kyhQoEqOs5NEm5';
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css'>
        <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css'>
        <link rel="icon" href="assets/img.png" />
        <title>ONLINE FEE PAYMENT</title>
    </head>
    <body>
        <div class="container">
            <table class="table table1 table-bordered">
                <tr width="50%" >YOUR DETAILS</tr>
                <tr>
                    <th width="30%">Roll Number</th>
                    <td width="2%">:</td>
                    <td><?php echo $ROLLNO; ?></td>
                </tr>
                <tr>
                    <th width="30%">Name</th>
                    <td width="2%">:</td>
                    <td><?php echo $Name; ?></td>
                </tr>
                <tr>
                    <th width="30%">Phone Number</th>
                    <td width="2%">:</td>
                    <td><?php echo $Phoneno; ?></td>
                </tr>
                <tr>
                    <th width="30%">Reservation</th>
                    <td width="2%">:</td>
                    <td><?php echo $Reservation; ?></td>
                </tr>
                <tr>
                    <th width="30%">Email id </th>
                    <td width="2%">:</td>
                    <td><?php echo $Emailid; ?></td>
                </tr>
                <tr>
                    <th width="30%">Addmission Category</th>
                    <td width="2%">:</td>
                    <td><?php echo $admissioncategory; ?></td>
                </tr>
            </table>
            <div style="height: 26px"></div>
        <form action="https://www.example.com/payment/success/" method="POST">
            <table class="table table-bordered">
                <tr>
                    <th width="30%">Total Fees</th>
                    <td width="2%">:</td>
                    <td><?php echo $totalfees ?> rupees</td>
                </tr>
                <tr>
                    <th width="30%">Due Fees</th>
                    <td width="2%">:</td>
                    <td><?php echo $Duefees ?> rupees</td>
                </tr>
            </table>
            <script
                src="https://checkout.razorpay.com/v1/checkout.js"
                data-key="<?php echo $apikey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
                data-amount="<?php echo $Duefees * 100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
                data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
                data-id="<?php echo 'OID' .rand(10,100).'END' ?>"// Replace with the order_id generated by you in the backend.
                data-buttontext="Pay with Razorpay"
                data-name="Vignan Institute of Technology and Science "
                data-description="College fees and bus fees"
                data-image="assets/img.png"
                data-prefill.name="<?php echo $Name ;?>"
                data-prefill.email="<?php echo $Emailid; ?>"
                data-prefill.contact="<?php echo $Phoneno; ?>"
                data-theme.color="#F37254"
                data-buttontext.color="#F37254"
            ></script>
            <input  type="hidden" custom="Hidden Element" name="hidden">
        </form>
        <button  onclick="location.href='/ivin/homepage.php'" type="submit" id="back" class="box" >BACK TO HOME PAGE</button>
        </div>
    </body>
</html>


<style>

 body {
    width: 100%;
    height: 100vh;
    margin: 0;
    background-color: #E2D1F9;
      color: #080808;
    font-family: Tahoma;
      font-size: 16px;
      font-weight: bolder;
  }

  html { overflow-y: scroll; }

  .container {
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    height: 100vh;
  }
  form, table {
    width: 60vw;
      max-width: 500px;
      min-width: 400px;
      margin: 0 auto;
    padding: 250px;
    text-align: center;
    background-color: #79A7D3;
    box-shadow: 0 0 36px 1px rgba(0, 0, 0, 0.2);
    border-radius: 10px;
    backdrop-filter: blur(20px);
    padding: 2rem;
    -webkit-border-radius: 10px;
    -moz-border-radius: 10px;
    -ms-border-radius: 10px;
    -o-border-radius: 10px;
  }
  
  .table1 {
    background-color: #79A7D3;
    padding: 50px;
    margin:10px;
    border-radius: 10px;
  }

  .box {
    background-color: #E2D1F9;
    color: black;
    display: block;
    padding: 13px;
    border-radius: 5px;
    outline: none;
    font-size: 18px;
    letter-spacing: 1.5px;
    font-weight: bold;
    width: 90%;
      max-width: 500px;
      min-width: 300px;
      margin: 0 auto;
    cursor: pointer;
    margin: 3rem;
    transition: all 0.1s ease-in-out;
    border: solid;
    border-color: black;
    border-width: 2px;
    -webkit-border-radius: 5px;
    -moz-border-radius: 5px;
    -ms-border-radius: 5px;
    -o-border-radius: 5px;
    -webkit-transition: all 0.1s ease-in-out;
    -moz-transition: all 0.1s ease-in-out;
    -ms-transition: all 0.1s ease-in-out;
    -o-transition: all 0.1s ease-in-out;
  }
  
  .box:hover {
    box-shadow: 0 0 10px 1px rgba(0, 0, 0, 0.15);
    transform: scale(1.02);
    -webkit-transform: scale(1.02);
    -moz-transform: scale(1.02);
    -ms-transform: scale(1.02);
    -o-transform: scale(1.02);
  }


</style>






